require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target "ug" do
	platform :ios, '10.0'

    use_frameworks!
    #消除第三方库警告

inhibit_all_warnings!

# Andrew新增

pod 'Masonry'             # 布局自动适应库
pod 'Toast', '~> 4.0.0'   # 类似Android提示库
pod 'IQKeyboardManager'   # 键盘库
pod 'LEEAlert'            # alert提示框
pod 'AvoidCrash'          # 防奔溃
pod 'BAWKWebView'         #web浏览器
pod 'SGQRCode', '~> 3.0.1'#二维码生成与扫描
pod 'YYWebImage'          #网络图
pod 'SGBrowserView'       # 动画弹出
pod 'DLPickerView'        # 一种支持单列数据选择，多列数据选择，plist读取数据选择的多功能数据选择器
pod 'STPickerView', '2.4' # 一个多功能的选择器,有城市选择，日期选择和单数组源自定的功能


# fish新增

#pod 'JRSwizzle'         # 方法交换库

#pod 'Aspects'           # 监听函数回调到Block

pod 'RegExCategories'   # 正则表达式库
pod 'YYCategories'      # Category 类型工具库（YYKit 组件之一）
pod 'DateTools'         # 日期工具
pod 'MJExtension'       # 字典转数据模型库
pod 'FSCalendar'        # 日历控件
pod 'SDWebImage'        # 异步图片加载+缓存
pod 'SDWebImage/GIF'    # 异步图片加载+缓存（GIF）
pod 'TZImagePickerController', '~> 3.2.8' # 相册浏览器
pod 'YYText', '~> 1.0.7'# YY大神的富文本框架

pod 'JPush', '3.2.2-noidfa'





# jspatch
pod 'JSPatch', :path => "../JSPatch/JSPatch.podspec"


# rn

pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
pod 'React', :path => '../node_modules/react-native/'
pod 'React-Core', :path => '../node_modules/react-native/'
pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  use_native_modules!


end
target "chat" do
	platform :ios, '10.0'

    use_frameworks!
    #消除第三方库警告

inhibit_all_warnings!

# 极光推送

pod 'JPush', '3.2.2-noidfa'

# Andrew新增

pod 'Masonry'             # 布局自动适应库
pod 'Toast', '~> 4.0.0'   # 类似Android提示库
pod 'IQKeyboardManager'   # 键盘库
pod 'LEEAlert'            # alert提示框
pod 'AvoidCrash'          # 防奔溃
pod 'BAWKWebView'         #web浏览器
pod 'SGQRCode', '~> 3.0.1'#二维码生成与扫描
pod 'SGBrowserView'       # 动画弹出
pod 'DLPickerView'        # 一种支持单列数据选择，多列数据选择，plist读取数据选择的多功能数据选择器
pod 'Toast', '~> 4.0.0' # 类似Android提示库
pod 'AvoidCrash'  # 防奔溃
pod 'BAWKWebView'  #web浏览器
pod 'SGQRCode', '~> 3.0.1'  #二维码生成与扫描
pod 'STPickerView', '2.4' # 一个多功能的选择器,有城市选择，日期选择和单数组源自定的功能

# fish新增

pod 'JRSwizzle'         # 方法交换库
pod 'Aspects'           # 监听函数回调到Block
pod 'RegExCategories'   # 正则表达式库
pod 'DateTools'         # 日期工具
pod 'MJExtension'       # 字典转数据模型库
pod 'FSCalendar'        # 日历控件
pod 'SDWebImage'        # 异步图片加载+缓存
pod 'SDWebImage/GIF'    # 异步图片加载+缓存（GIF）
pod 'JPush', '3.2.2-noidfa'
pod 'YYText', '~> 1.0.7'
pod 'YYCategories'      # Category 类型工具库（YYKit 组件之一）
pod 'YYWebImage'          #网络图

# xionghx

pod 'Starscream', '~> 3.1.1'
pod 'Moya/RxSwift', '~> 14.0.0-alpha.1'
pod 'ObjectMapper', '~> 3.3.0'
pod 'RxSwift', '~> 5.0.0'
pod 'RxCocoa', '~> 5.0.0'
pod 'RxRelay', '~> 5.0.0'
pod 'RxAlertController', '~> 5.0.0'

# pod 'Moya-ObjectMapper/RxSwift', '~> 2.8'

pod 'NSObject+Rx', '~> 5.0.0'
pod 'SnapKit', '~> 4.0.1'
pod 'MJRefresh', '~> 3.1.15.7'
pod 'MessageKit', '~> 3.0.0'
pod 'SKPhotoBrowser', '~> 6.1.0'
pod 'DeviceKit', '~> 2.3.0'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'Kingfisher', '~> 5.6.0'
pod 'IQKeyboardManagerSwift', '~> 6.3.0'
pod 'ESTabBarController-swift', '~> 2.7'
pod 'pop', '~> 1.0.12'
pod 'CryptoSwift', '~>1.1.3'
pod 'SwiftyJSON', '~>5.0.0'
pod 'RxDataSources', '~> 4.0.1'
pod 'SwiftGifOrigin', '~> 1.7.0'
pod 'TZImagePickerController', '~> 3.2.8'
pod 'RxOptional', '~> 4.1.0'
pod 'SVGKit', '~> 3.0.0-beta3'
end


